services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Ladataan nginx-konfiguraatio
      - ./dashboard:/usr/share/nginx/html # Ladataan dashboard-tiedostot
    ports:
      - "80:80" # Kuunnellaan HTTP:ää portissa 80
    depends_on:
      - iot-app # Odottaa, että iot-app-palvelu käynnistyy
    networks:
      my_network:
        ipv4_address: 192.168.1.10 # Kiinteä IP-osoite nginxille

  iot-app:
    build: . # Rakenna Dockerfile tämän palvelun määrittelemiseksi
    ports:
      - "8080:8080" # Exposaa backend-portti
    networks:
      my_network:
        ipv4_address: 192.168.1.20 # Kiinteä IP backendille

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt # SSL-varmenteet tallennetaan tähän hakemistoon
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"
